
# Transaction status
NOT_STARTED = "NOT_STARTED"
SETUP_DONE = "SETUP_DONE"
FORWARDING = "FORWARDING"
RELEASING = "RELEASING"
REVOKING = "REVOKING"
FAILED = "FAILED"
SUCCESS = "SUCCESS"

TX_ER_CHECKING = "TX_ER_CHECKING"
TX_ER_PUBLISHED = "TX_ER_PUBLISHED"
INSTANT_REVOKING = "INSTANT_REVOKING"
GO_IDLE = "GO_IDLE"
FORCING_REVOKE = "FORCING_REVOKE"
RELEASE_ALL="RELEASE_ALL"
FINISHED_FORWARDING = "FINISHED_FORWARDING"
REVOKE_ALL="REVOKE_ALL"



# Contract status
LOCKED = "LOCKED"
RELEASED = "RELEASED"
REVOKED = "REVOKED"